fixed deprications
Oralordos/glass-syntax pull request #3
Opened 2017-09-11 21:44 UTC by Shenung

2017-09-11 21:57 UTC, oralordos requested changes
Some duplicates in the less code that need to be addressed.

2017-09-11 21:57 UTC, Oralordos commented on styles/syntax-variables.less
> +@syntax-background-color: rgba(0, 0, 0, 0.5);
Why does this need to change?

2017-09-11 21:57 UTC, Oralordos commented on styles/base.less
> +atom-text-editor, atom-text-editor {
One of these should be removed, you don't need to have the same thing on both sides of a comma.

2017-09-11 21:57 UTC, Oralordos commented on styles/base.less
> +atom-text-editor .search-results .syntax--marker .region, atom-text-editor .search-results .syntax--marker .region {
Same here on the comment thing.

2017-09-11 21:57 UTC, Oralordos commented on styles/base.less
> +atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region {
And here too with the comma.

2017-09-14 17:59 UTC, Shenung commented on styles/syntax-variables.less
> +@syntax-background-color: rgba(0, 0, 0, 0.5);
because

2017-09-14 18:03 UTC, oralordos approved these changes

2017-09-14 18:03 UTC, merged